---
- name: Instalar Docker no Host Remoto
  hosts: codecraft_vm
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
      register: apt_latest

    - name: Instalar pacotes necessários
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: apt_latest is succeeded

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Garantir que o Docker esteja rodando
      systemd:
        name: docker
        state: started
        enabled: yes
       
    - name: Clonar repositório Git
      become: yes
      become_user: ubuntu
      git:
        repo: 'https://github.com/codecrafthackweek/backend.git'
        dest: /home/ubuntu/app/backend
        version: main
        accept_hostkey: yes
        
    - name: Copiar o Dockerfile do repositório
      copy:
        src: Dockerfile
        dest: /home/ubuntu/app
        
    - name: Construir a imagem Docker
      command: docker build -t api-csharp .
      args:
        chdir: /home/ubuntu/app

    - name: Executar o contêiner Docker
      command: docker run -d -p 8080:80 api-csharp
